cc_library(
	name = "accounts-include",
	srcs = ["Account.cpp", "Account_Util.cpp", "CheckingAccount.cpp", "SavingsAccount.cpp", "TrustAccount.cpp"],
	hdrs = ["Account.h", "Account_Util.h", "CheckingAccount.h", "SavingsAccount.h", "TrustAccount.h"],
	visibility = ["//src:__pkg__"],
	)
